### ISSUE TITLE
Manual KMIP testing with PyKMIP

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#564]

**Comment by ximon18** [comment]
Tested using Krill commit eb97735 (the current head of the `issue-698-record-keys-on-upgrade` branch) and PyKMIP 0.10.0 on Ubuntu 21.10, with PyKMIP configuration and startup script taken from the `test-resources/pykmip/` directory in that Krill commit.

Krill was installed like so:

```
$ cargo install --git https://github.com/NLnetLabs/krill --rev eb97735 --locked --features hsm
```

The Krill config file looked like this:
```toml
admin_token = "abc"
data_dir = "/tmp/krill"
service_uri = "https://localhost:3000/"
log_level = "trace"
log_type = "stderr"

[[signers]]
type = "KMIP"
host = "localhost"
server_ca_cert_path = "<path/to/krill/git/checkout>/test-resources/pykmip/ca.crt"
client_cert_path = "<path/to/krill/git/checkout>/test-resources/pykmip/server.crt"
client_cert_private_key_path = "<path/to/krill/git/checkout>/test-resources/pykmip/server.key"
deficient = true
```

**Note:** `deficient = true` is set because PyKMIP 0.10.0 reports that it is unable to modify attributes but when the `ModifyAttribute` operation is attempted it succeeds so we ignore the claim that it is unsupported, otherwise Krill would refuse to use the PyKMIP server.

Run PyKMIP in one terminal:
```
$ cd <path/to/krill/git/checkout>/test-resources/pykmip
$ ./run-server.py
```

Run Krill in another terminal:
```
$ ~/.cargo/bin/krill -c /tmp/krill.conf
```

Krill configures itself to use the KMIP signer for and a fallback OpenSSL signer:
```
[INFO] ... Configuring signer 'KMIP' (type: KMIP, default: true, oneoff: false, random: false)
[INFO] ... Configuring signer 'Fallback OpenSSL signer' (type: OpenSSL, default: false, oneoff: true, random: true)
```

In a third terminal use `krillc` to create a CA:

```
$ export KRILL_CLI_TOKEN=abc
$ ~/cargo/bin/krillc add --ca some_ca
```

On creation of a CA, Krill attempts to initialize the signers and contact the KMIP server:

```
[WARN] ... [KMIP] Ignoring KMIP server lacking support for one or more required operations: ModifyAttribute
[INFO] ... [KMIP] Using KMIP server 'PyKMIP 0.10.0 Software Server' at localhost:5696
...
[INFO] ... Signer 'KMIP' is ready for use
[INFO] ... Signer 'Fallback OpenSSL signer' is ready for use
```

Next register Krill with the NLnet Labs public testbed as a publisher:

```
$ ~/.cargo/bin/krillc repo request --ca some_ca > /tmp/req.xml
.. submit req.xml to the testbed ...
$ ~/.cargo/bin/krillc repo configure --ca some_ca --response ~/Downloads/repository_response.xml
```

Next register Krill as a child CA under the NLnet Labs public testbed:

```
$ ~/.cargo/bin/krillc parents request --ca some_ca > /tmp/req2.xml
.. submit req2.xml to the testbed ..
$ ~/.cargo/bin/krillc parents add --ca some_ca --response ~/Downloads/parent_response.xml --parent testbed
```

Finally, create a ROA:

```
$ ~/.cargo/bin/krillc roas update --ca some_ca --add "10.0.0.1/32 => 18"
```

There will now be two keys mapped to the KMIP signer and none to the OpenSSL signer:

```
$ jq '.signer_name, .signer_identity.private_key_internal_id, .keys' /tmp/krill/signers/6b71e734-e097-4629-99fe-00bb4ad2d85e/snapshot.json 
"KMIP"
"2"
{
  "630F712B963209973FB9064D1A9D5D449F2B8AD3": "5:6",
  "45BE385D018E1C9301ECE9DA297554805D84AD0B": "3:4"
}

$ q '.signer_name, .signer_identity.private_key_internal_id, .keys' /tmp/krill/signers/e4ec48f1-715b-4c4e-a1ef-f7918f65b9ee/snapshot.json 
"Fallback OpenSSL signer"
"1AFB19EBC7A569E91FE9AD991112953487A33FFD"
{}
```

And the OpenSSL keys directory contains only the identity key that Krill created for it:

```
$ ls -1 /tmp/krill/keys/
1AFB19EBC7A569E91FE9AD991112953487A33FFD
```
