### ISSUE TITLE
Infinite redirect loop when using OIDC login

### ISSUE THREAD

**Issue by TheEnbyperor** [NLnetLabs/krill#608]
# Symptoms

* Load up Krill home page
* Correctly redirected to OIDC IdP
* Successful redirect back to Krill
* Server side debug logs indicate authorization code exchange successful 
* Web browser redirected back to Krill home page with `token=blablabla` in the query fragment
* Should login to Krill, however the whole process restarts

This appears not to be related to incorrect roles, as setting a different value for `krill_role` in the JWT claims correctly results in Krill showing a permission denied error.

Nothing is logged by JS on the client side to indicate an error.

# Environment

Krill running in Docker on Kubernetes, with image `nlnetlabs/krill:v0.9.0`. Host machine in x86_64.

# Config extract

```toml
auth_type = "openid-connect"

[auth_openidconnect]
issuer_url = "https://sso.as207960.net/auth/realms/master"
client_id = "krill"
client_secret = "<snip>"

[auth_openidconnect.claims]
id = { jmespath="sub" }
role = { jmespath="krill_role[0]" }
```
